nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"
checksumBehavior: "ignore"   # ou "update" si tu veux régénérer
enableGlobalCache: true      # évite de dépendre de .yarn/cache commité
