# .yarnrc.yml
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
checksumBehavior: ignore      # (ou: update)
enableGlobalCache: true
# (recommandé si tu as une version de Yarn committée)
# yarnPath: .yarn/releases/yarn-<ta-version>.cjs
