# .yarnrc.yml

# Utilise le mode node-modules (plus simple pour Railway/Nixpacks)
nodeLinker: node-modules

# Force le bon registry officiel (évite les checksums foireux)
npmRegistryServer: "https://registry.npmjs.org"

# Ignore les erreurs de checksum (tu peux remettre "update" plus tard)
checksumBehavior: ignore

# Permet à Yarn d’utiliser un cache global plutôt qu’un dossier .yarn/cache commité
enableGlobalCache: true
